server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://120.55.127.129:3310/intelligentsports?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: abc123.
    driver-class-name: com.mysql.cj.jdbc.Driver
